<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNcl4d2u\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNcl4d2u/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNcl4d2u.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNcl4d2u\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNcl4d2u\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ncl4d2u',
    'container.build_id' => '40aebb1f',
    'container.build_time' => 1525710408,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNcl4d2u');
