<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQsa765q\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQsa765q/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQsa765q.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQsa765q\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQsa765q\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Qsa765q',
    'container.build_id' => '0e7db411',
    'container.build_time' => 1526228874,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQsa765q');
